whitespace_typedefs = true
whitespace_ops_in_indices = true
remove_extra_newlines = true
always_for_in = false
conditional_to_if = false
normalize_line_endings = auto
separate_kwargs_with_semicolon = true