language: julia
os:
  - osx
  - linux
julia:
  - 0.6
notifications:
  email: false
addons:
  apt:
    packages:
    - hdf5-tools
# script:
#   - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
#   - julia -e 'Pkg.clone(pwd());'
#   $ - julia -e 'ENV["MADS_NO_PYTHON"]=""; ENV["MADS_NO_PLOT"]=""; Pkg.build("Mads"); Pkg.test("Mads"; coverage=true)'
#   - julia -e 'ENV["MADS_TRAVIS"]=""; Pkg.build("Mads"); Pkg.test("Mads"; coverage=true)'
after_success:
  - julia -e 'cd(Pkg.dir("Mads")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder()); Codecov.submit(Codecov.process_folder())'
