site_name: MADS
site_url: http://madsjulia.github.io/Mads.jl
theme: material

repo_url: https://github.com/madsjulia/Mads.jl
site_description: "Model Analysis and Decision Support"
site_author: "Velimir monty Vesselinov"

google_analytics: ['UA-25717430-1', 'mads.lanl.gov']

extra_css:
- assets/Documenter.css

nav:
- Home: index.md
- Installation: installation.md
- Getting started: getting_started.md
- Examples:
  - Setup: Examples/setup.md
  - Decision Analysis: Examples/bigdt/source_termination/index.md
  - Information Gap Decision Analysis: Examples/infogap/index.md
  - Uncertainty Quantification: Examples/bayesian_sampling/index.md
  - Machine Learning: Examples/machine_learning/index.md
  - Contaminant Source Identification: Examples/contaminant_source_identification/index.md
  - Blind Source Separation: Examples/blind_source_separation/index.md
  - Contaminant Transport: Examples/contamination/index.md
  - ODE Analysis: Examples/ode/index.md
- Notebooks: Notebooks/index.md
- Examples Links: Examples/index.md
- Model Coupling: model_coupling.md
- Testing & Verification: test.md
- Functions: functions.md
- Modules:
  - Mads: Modules/Mads.md
  - AffineInvariantMCMC: Modules/AffineInvariantMCMC.md
  - Anasol: Modules/Anasol.md
  - BIGUQ: Modules/BIGUQ.md
  - DocumentFunction: Modules/DocumentFunction.md
  - GeostatInversion: Modules/GeostatInversion.md
  - MetaProgTools: Modules/MetaProgTools.md
  - ReusableFunctions: Modules/ReusableFunctions.md
  - RobustPmap: Modules/RobustPmap.md
  - SVR: Modules/SVR.md
- Acknowledgments: acknowledgments.md
- License: copying.md

markdown_extensions:
  - extra
  - tables
  - toc
  - footnotes
  - admonition
  - codehilite
  - fenced_code
#  - mdx_math:
#      enable_dollar_delimiter: True #for use of inline $..$

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js?config=TeX-AMS_HTML
  - assets/mathjaxhelper.js

theme:
  name: 'material'
  palette:
    primary: 'orange'
    accent: 'teal'
  logo: 'logo/mads_black_swan_logo.png'
  favicon: mads-favicon.ico
  author:
    github: madsjulia
